### apply() - Calculate Project Salary Next Year

In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset ['train'].to_pandas ()

df ['job_posted_date'] = pd.to_datetime(df ['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df['salary_year_avg']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [4]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [5]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [6]:
help(df.apply)

Help on method apply in module pandas.core.frame:

apply(func: 'AggFuncType', axis: 'Axis' = 0, raw: 'bool' = False, result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None, args=(), by_row: "Literal[False, 'compat']" = 'compat', engine: "Literal['python', 'numba']" = 'python', engine_kwargs: 'dict[str, bool] | None' = None, **kwargs) method of pandas.core.frame.DataFrame instance
    Apply a function along an axis of the DataFrame.

    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument.

    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:

        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.

    raw : bool, default False
        Determines if row or column is passed as a Series or ndarray object:

        * ``False`` : passes each row or column as a Series to the
          function.
        * ``True`` : the passed function will receive ndarray objects
          instead.
          If you are just applying a NumPy reduction function this will
          achieve much better performance.

    result_type : {'expand', 'reduce', 'broadcast', None}, default None
        These only act when ``axis=1`` (columns):

        * 'expand' : list-like results will be turned into columns.
        * 'reduce' : returns a Series if possible rather than expanding
          list-like results. This is the opposite of 'expand'.
        * 'broadcast' : results will be broadcast to the original shape
          of the DataFrame, the original index and columns will be
          retained.

        The default behaviour (None) depends on the return value of the
        applied function: list-like results will be returned as a Series
        of those. However if the apply function returns a Series these
        are expanded to columns.
    args : tuple
        Positional arguments to pass to `func` in addition to the
        array/series.
    by_row : False or "compat", default "compat"
        Only has an effect when ``func`` is a listlike or dictlike of funcs
        and the func isn't a string.
        If "compat", will if possible first translate the func into pandas
        methods (e.g. ``Series().apply(np.sum)`` will be translated to
        ``Series().sum()``). If that doesn't work, will try call to apply again with
        ``by_row=True`` and if that fails, will call apply again with
        ``by_row=False`` (backward compatible).
        If False, the funcs will be passed the whole Series at once.

        .. versionadded:: 2.1.0

    engine : {'python', 'numba'}, default 'python'
        Choose between the python (default) engine or the numba engine in apply.

        The numba engine will attempt to JIT compile the passed function,
        which may result in speedups for large DataFrames.
        It also supports the following engine_kwargs :

        - nopython (compile the function in nopython mode)
        - nogil (release the GIL inside the JIT compiled function)
        - parallel (try to apply the function in parallel over the DataFrame)

          Note: Due to limitations within numba/how pandas interfaces with numba,
          you should only use this if raw=True

        Note: The numba compiler only supports a subset of
        valid Python/numpy operations.

        Please read more about the `supported python features
        <https://numba.pydata.org/numba-doc/dev/reference/pysupported.html>`_
        and `supported numpy features
        <https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html>`_
        in numba to learn what you can or cannot use in the passed function.

        .. versionadded:: 2.2.0

    engine_kwargs : dict
        Pass keyword arguments to the engine.
        This is currently only used by the numba engine,
        see the documentation for the engine argument for more information.
    **kwargs
        Additional keyword arguments to pass as keywords arguments to
        `func`.

    Returns
    -------
    Series or DataFrame
        Result of applying ``func`` along the given axis of the
        DataFrame.

    See Also
    --------
    DataFrame.map: For elementwise operations.
    DataFrame.aggregate: Only perform aggregating type operations.
    DataFrame.transform: Only perform transforming type operations.

    Notes
    -----
    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    Examples
    --------
    >>> df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
    >>> df
       A  B
    0  4  9
    1  4  9
    2  4  9

    Using a numpy universal function (in this case the same as
    ``np.sqrt(df)``):

    >>> df.apply(np.sqrt)
         A    B
    0  2.0  3.0
    1  2.0  3.0
    2  2.0  3.0

    Using a reducing function on either axis

    >>> df.apply(np.sum, axis=0)
    A    12
    B    27
    dtype: int64

    >>> df.apply(np.sum, axis=1)
    0    13
    1    13
    2    13
    dtype: int64

    Returning a list-like will result in a Series

    >>> df.apply(lambda x: [1, 2], axis=1)
    0    [1, 2]
    1    [1, 2]
    2    [1, 2]
    dtype: object

    Passing ``result_type='expand'`` will expand list-like results
    to columns of a Dataframe

    >>> df.apply(lambda x: [1, 2], axis=1, result_type='expand')
       0  1
    0  1  2
    1  1  2
    2  1  2

    Returning a Series inside the function is similar to passing
    ``result_type='expand'``. The resulting column names
    will be the Series index.

    >>> df.apply(lambda x: pd.Series([1, 2], index=['foo', 'bar']), axis=1)
       foo  bar
    0    1    2
    1    1    2
    2    1    2

    Passing ``result_type='broadcast'`` will ensure the same shape
    result, whether list-like or scalar is returned by the function,
    and broadcast it along the axis. The resulting column names will
    be the originals.

    >>> df.apply(lambda x: [1, 2], axis=1, result_type='broadcast')
       A  B
    0  1  2
    1  1  2
    2  1  2

In [9]:
def projected_salary(salary):
    return salary * 1.03

df['salary_year_avg'].apply(projected_salary)

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [10]:
df_salary = df[pd.notna(df['salary_year_avg'])]

def projected_salary(salary):
    return salary * 1.03

df_salary['salary_year_avg'].apply(projected_salary)

28        112785.00
77        144200.00
92        123600.00
100       235068.66
109        91670.00
            ...
785624    143392.48
785641    154500.00
785648    228531.25
785682    162225.00
785692    162225.00
Name: salary_year_avg, Length: 22003, dtype: float64

In [ ]:
df_salary = df[pd.notna(df['salary_year_avg'])]

def projected_salary(salary):
    return salary * 1.03

df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)

df_salary[['salary_year_avg', 'salary_year_inflated']]

C:\Users\Swayam Jevoor\AppData\Local\Temp\ipykernel_6932\522119344.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [14]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

def projected_salary(salary):
    return salary * 1.03

df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [16]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [17]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'] * 1.03

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [23]:
type(df['job_skills'])

pandas.core.series.Series

In [25]:
list(df['job_skills'])

[None,
 "['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']",
 "['python', 'sql', 'c#', 'azure', 'airflow', 'dax', 'docker', 'kubernetes', 'jenkins']",
 "['python', 'c++', 'java', 'matlab', 'aws', 'tensorflow', 'keras', 'pytorch']",
 "['bash', 'python', 'oracle', 'aws', 'ansible', 'puppet', 'jenkins', 'gitlab', 'git']",
 "['python', 'sql', 'gcp']",
 "['sql', 'python', 'java', 'sql server', 'gcp', 'bigquery', 'hadoop']",
 "['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigquery', 'databricks', 'redshift', 'airflow', 'kafka', 'spark']",
 "['excel', 'powerpoint', 'power bi']",
 "['sql', 'python', 'r', 'mongodb', 'mongodb', 'sql server', 'azure', 'pandas', 'spark', 'windows', 'excel']",
 "['python', 'databricks', 'azure', 'spark']",
 "['python', 'qlik']",
 "['sql', 'php', 'excel', 'power bi', 'sap', 'jira']",
 "['python', 'sql', 'go', 'ruby', 'ruby', 'javascript', 'aws', 'flask', 'fastapi', 'terraform']",
 "['mongodb', 'mongodb']",
 "['python', 'sql', 'power bi']",
 "['powershell', 'python', 'sql', 'mysql', 'sql server', 'databricks', 'azure']",
 "['go', 'apl', 'excel']",
 "['sql', 'python', 'r', 'redshift', 'pandas', 'excel', 'looker', 'tableau']",
 "['r', 'sql', 'python', 'scala', 'java', 'c++', 'hadoop', 'tableau']",
 "['r', 'python', 'sql', 'pandas', 'numpy', 'scikit-learn', 'matplotlib', 'hadoop', 'spark']",
 None,
 "['sql', 'scala', 'java', 'python', 'mongodb', 'mongodb', 'elasticsearch', 'cassandra', 'neo4j', 'aws', 'azure', 'gcp', 'hadoop', 'spark', 'airflow', 'kafka', 'docker', 'kubernetes']",
 "['python', 'r']",
 "['python']",
 "['sql']",
 None,
 "['python', 'r', 'java']",
 "['gdpr', 'excel']",
 None,
 "['scala', 'python', 'nosql', 'mongo', 'shell', 'mysql', 'cassandra', 'redshift', 'snowflake', 'aws', 'azure', 'hadoop', 'kafka', 'spark']",
 "['sql']",
 "['python', 'azure', 'databricks', 'pyspark', 'pandas', 'hadoop', 'spark', 'nltk']",
 "['sql', 'python', 'r', 'azure', 'databricks', 'pyspark', 'flow']",
 "['sap']",
 "['python', 'sql', 'neo4j', 'databricks', 'azure', 'spark', 'pyspark', 'flask']",
 None,
 "['python', 'sql', 'nosql', 'aws', 'gcp', 'azure', 'spark', 'hadoop', 'docker', 'terraform', 'jenkins', 'git']",
 "['sql', 'python', 'databricks', 'power bi', 'excel', 'word', 'powerpoint']",
 "['sql', 'python']",
 None,
 "['r', 'sql', 'python', 'scala', 'java', 'c++', 'hadoop', 'tableau']",
 "['python', 'sql', 'aws', 'pyspark', 'docker', 'jira']",
 "['sql', 'sql server']",
 "['python', 'java', 'scala']",
 "['sql', 'python']",
 "['sas', 'sas', 'r', 'python', 'vba', 'sql', 'java', 'sql server', 'pandas', 'spss', 'tableau', 'excel', 'power bi']",
 "['sql', 'python', 'scala', 'nosql', 'java', 'c', 'spark', 'hadoop', 'kafka', 'power bi', 'microstrategy', 'cognos', 'sap']",
 "['javascript', 'python', 'gcp', 'aws', 'selenium']",
 "['excel']",
 "['python', 'sql', 'pytorch', 'pandas']",
 "['python', 'java', 'aws', 'databricks', 'spark']",
 "['sql', 'html', 'css', 'javascript', 'lua', 'redshift', 'snowflake', 'databricks', 'linux', 'tableau', 'git']",
 "['sql', 'python', 'aws', 'looker']",
 "['snowflake', 'spark', 'hadoop', 'tableau', 'qlik']",
 "['python', 'sql', 'azure']",
 None,
 "['sql', 'mysql', 'postgresql', 'sql server', 'aws', 'azure', 'power bi', 'tableau']",
 "['python', 'aws', 'gcp']",
 "['sql', 'hadoop', 'kubernetes']",
 "['r', 'python', 'sql', 'tableau', 'power bi']",
 "['sql', 'nosql', 'python', 'java', 'c++', 'scala', 'cassandra', 'hadoop', 'spark', 'kafka']",
 "['python', 'go']",
 "['sql', 'mongodb', 'mongodb', 'python', 'dynamodb', 'azure', 'aws', 'hadoop', 'gdpr', 'jenkins', 'docker', 'kubernetes']",
 None,
 "['sql', 'hadoop', 'spark', 'jenkins', 'chef', 'flow']",
 "['sql', 'gcp', 'looker', 'tableau']",
 "['excel']",
 "['r', 'zoom']",
 "['sql']",
 "['python', 'go', 'oracle', 'scikit-learn', 'tensorflow', 'pytorch']",
 "['sql', 'excel']",
 "['power bi']",
 "['word', 'excel', 'powerpoint', 'outlook']",
 "['sql', 'r', 'python', 'tableau', 'power bi']",
 "['perl', 'python', 'sql', 'r', 'matlab', 'javascript', 'linux', 'git', 'jira']",
 "['sql', 'python', 'r', 'excel', 'tableau', 'power bi']",
 "['mongodb', 'mongodb', 'python', 'r', 'sql', 'mysql', 'mariadb', 'oracle', 'spark', 'tableau', 'kubernetes']",
 "['sql', 'excel', 'looker', 'sap']",
 "['sas', 'sas', 'word', 'excel']",
 "['gcp', 'graphql', 'kubernetes']",
 None,
 None,
 "['bash', 'python', 'aws', 'linux', 'splunk', 'github', 'jenkins', 'kubernetes', 'docker', 'ansible', 'terraform']",
 "['python', 'r', 'sql', 'javascript', 'aws', 'snowflake', 'react', 'airflow', 'angular', 'git', 'jenkins', 'kubernetes']",
 "['python', 'pytorch']",
 "['java', 'python', 'php', 'sql', 'shell', 'gcp', 'aws', 'spark', 'hadoop', 'kafka', 'linux']",
 "['r', 'python', 'tableau', 'qlik']",
 "['python', 'java', 'sql', 'javascript', 'azure', 'aws', 'databricks', 'snowflake', 'redshift', 'bigquery', 'spark', 'jupyter', 'tensorflow', 'react', 'angular', 'vue', 'tableau', 'power bi']",
 "['java', 'scala', 'python', 'nosql', 'sql', 'mongo', 'shell', 'mysql', 'cassandra', 'redshift', 'snowflake', 'aws', 'azure', 'hadoop', 'kafka', 'spark', 'unix', 'linux']",
 "['python', 'sql', 'r', 'java', 'bash', 'react', 'hadoop', 'spark', 'unix', 'tableau', 'git']",
 "['sql', 'python', 'tensorflow', 'numpy', 'pandas', 'excel', 'tableau']",
 "['sql', 'python']",
 "['oracle', 'azure', 'power bi', 'excel', 'word', 'powerpoint']",
 "['javascript', 'python', 'sql', 'aws', 'azure', 'power bi', 'tableau']",
 "['nosql', 'mongodb', 'mongodb', 'elasticsearch', 'mysql', 'redis', 'neo4j', 'hadoop', 'kafka', 'tableau', 'docker', 'kubernetes']",
 "['sql', 'r', 'python', 'sql server', 'azure', 'aws', 'spark', 'sap']",
 None,
 "['python', 'aws', 'databricks', 'spark']",
 "['scala', 'java', 'golang', 'sql', 'react', 'spark', 'hadoop', 'linux']",
 "['sql', 'r', 'python', 'express']",
 "['sql']",
 "['python', 'sql', 'r', 'java']",
 "['sql', 'nosql', 'aws', 'gcp', 'azure', 'spark', 'git', 'docker', 'terraform']",
 "['c++', 'java', 'snowflake']",
 "['python', 'bash', 'sql', 'aurora', 'numpy', 'matplotlib', 'pandas', 'linux', 'git', 'docker']",
 "['python']",
 "['python', 'sql', 'nosql', 'mongodb', 'mongodb', 'cassandra', 'aws', 'azure', 'gcp', 'power bi', 'qlik', 'tableau', 'ansible', 'git', 'jenkins']",
 "['azure', 'excel', 'unity']",
 "['python', 'r', 'alteryx', 'tableau']",
 "['sql', 'nosql', 'mongodb', 'mongodb', 'python', 'java', 'mysql', 'aws', 'gcp', 'azure', 'react', 'hadoop', 'spark', 'tableau', 'flow', 'docker', 'kubernetes']",
 "['python', 'sql', 'c#', 'r']",
 "['sql', 't-sql', 'sql server', 'azure', 'snowflake', 'git', 'jira', 'confluence']",
 "['python', 'sql', 'html', 'css', 'javascript', 'azure', 'linux', 'excel']",
 "['javascript', 'typescript', 'sql', 'python', 'r', 'azure', 'aws', 'pyspark', 'outlook', 'power bi', 'tableau', 'qlik']",
 "['scala', 'azure']",
 "['r', 'python', 'sql', 't-sql', 'hadoop', 'spark', 'tableau']",
 None,
 "['python', 'r', 'sql', 'go', 'bigquery']",
 "['sql', 'r', 'python', 'azure', 'snowflake', 'sap', 'powerpoint', 'excel', 'power bi']",
 "['python', 'azure', 'databricks', 'spark', 'jupyter', 'docker']",
 "['python', 'scala', 'sql', 'aws', 'azure', 'gcp', 'snowflake', 'bigquery', 'airflow', 'hadoop', 'kafka', 'spark', 'docker', 'github', 'gitlab', 'terraform', 'ansible', 'jira']",
 None,
 "['sql', 'excel', 'word', 'powerpoint', 'outlook', 'power bi']",
 "['sql', 'python', 'r', 'hadoop', 'spark', 'git', 'jira']",
 "['sql', 'shell', 'python', 'aws']",
 "['sql', 'python', 'sql server', 'excel', 'flow', 'git']",
 "['sql', 'snowflake']",
 "['python', 'ruby', 'ruby', 'sql', 'snowflake', 'aws', 'kafka', 'tableau', 'docker', 'kubernetes']",
 "['python', 'sql', 'nosql', 'aws']",
 "['sap']",
 "['sql', 'cassandra', 'aws', 'hadoop', 'spark', 'kafka', 'word', 'docker', 'kubernetes']",
 "['sql', 'python', 'nosql', 'azure', 'databricks', 'power bi']",
 "['python', 'sql', 'matlab', 'aws', 'azure']",
 "['scala', 'sql', 'aws', 'redshift', 'snowflake', 'spark', 'hadoop', 'airflow', 'jira']",
 "['python', 'go', 'javascript', 'gdpr']",
 "['python', 'sql', 'snowflake', 'aws', 'scikit-learn', 'keras', 'tensorflow', 'pytorch', 'airflow', 'pyspark', 'git']",
 "['sql', 'r', 'python', 'snowflake', 'looker', 'git']",
 "['sql', 'tableau', 'spss', 'sap']",
 "['python', 'aws', 'spark', 'pandas', 'pyspark', 'sap', 'tableau']",
 None,
 "['typescript', 'html', 'css', 'javascript', 'angular', 'sap']",
 "['python', 'r', 'sql', 'azure', 'power bi', 'excel', 'powerpoint']",
 None,
 "['sql', 'oracle', 'aws', 'azure', 'gcp', 'ssis']",
 "['python', 'sql', 'aws', 'word']",
 "['golang', 'scala', 'python', 'java', 'hadoop', 'spark']",
 "['sass', 'javascript', 'typescript', 'aws', 'react', 'git', 'npm']",
 "['python', 'sql', 'tableau']",
 "['python', 'sql', 'aws', 'azure', 'gcp', 'spark', 'tableau', 'microstrategy', 'qlik', 'git', 'jira', 'confluence']",
 "['excel']",
 "['sas', 'sas', 'sql', 'python', 'r', 'excel', 'tableau']",
 "['react', 'docker']",
 "['sql', 'tableau']",
 "['python', 'sas', 'sas', 'r', 'sql', 'nosql', 'hadoop', 'spark', 'jquery']",
 "['sql', 'python', 'unix', 'excel', 'jira']",
 "['sql', 'excel']",
 "['python', 'sql', 'snowflake', 'airflow', 'tableau', 'power bi']",
 "['python', 'sql', 'java', 'scala', 'snowflake', 'redshift', 'aws', 'azure', 'databricks', 'spark', 'excel']",
 "['sql']",
 "['azure']",
 "['t-sql', 'matplotlib', 'numpy', 'pandas', 'ssis', 'dax']",
 "['python', 'postgresql', 'dynamodb', 'aws', 'fastapi', 'flask', 'django', 'docker', 'ansible', 'bitbucket']",
 "['sql', 'python', 'postgresql']",
 "['sas', 'sas', 'vba']",
 "['python', 'mongodb', 'mongodb', 'sql', 'nosql', 'postgresql', 'redshift', 'aws', 'airflow', 'django']",
 "['sql', 'mongo', 'sql server', 'azure', 'kubernetes']",
 "['sql', 'gcp', 'oracle', 'airflow', 'microstrategy', 'power bi', 'github']",
 None,
 "['firebase', 'firebase']",
 "['sql', 'excel']",
 "['sas', 'sas', 'sql']",
 "['java', 'scala', 'sql', 'python', 'azure', 'bigquery', 'databricks', 'gcp', 'spark', 'hadoop']",
 "['sql', 'azure', 'aws', 'power bi']",
 "['python', 'r', 'postgresql', 'pandas', 'tableau', 'splunk', 'docker', 'kubernetes']",
 "['sap', 'excel']",
 "['python', 'java', 'r', 'c++', 'aws', 'azure', 'spark', 'hadoop', 'docker', 'kubernetes']",
 "['java', 'python', 'r', 'gcp', 'aws', 'azure', 'scikit-learn', 'unix', 'terraform']",
 "['sql']",
 "['jira', 'confluence']",
 "['excel', 'powerpoint']",
 "['sql', 'r', 'python', 'tableau']",
 "['python', 'elasticsearch', 'postgresql', 'neo4j', 'aws', 'spark', 'pytorch', 'jupyter', 'hadoop', 'kubernetes']",
 "['sql', 'python', 'java', 'scala', 'spark']",
 "['c', 'terminal']",
 "['python', 'shell', 'azure', 'databricks', 'airflow', 'kafka']",
 "['python', 'sql', 'sql server', 'aws', 'redshift']",
 "['azure', 'splunk']",
 "['python', 'excel', 'dax', 'power bi', 'smartsheet']",
 "['sharepoint', 'jira', 'confluence']",
 "['sas', 'sas', 'sql']",
 "['java', 'scala', 'python', 'nosql', 'sql', 'mongo', 'shell', 'mysql', 'cassandra', 'redshift', 'snowflake', 'aws', 'azure', 'hadoop', 'kafka', 'spark']",
 "['r']",
 "['java', 'javascript', 'c++', 'sas', 'sas', 'python', 'oracle', 'spring', 'tableau', 'docker', 'jenkins']",
 "['python', 'sql', 'excel', 'ms access', 'powerpoint']",
 "['python', 'sql', 'git']",
 "['sql', 'visual basic', 'sql server', 'tableau']",
 "['sql', 'python', 'java', 'scala', 'snowflake', 'aws', 'azure', 'airflow', 'looker']",
 "['aws']",
 "['go', 'sql', 'python', 'windows']",
 "['aws']",
 "['mongodb', 'mongodb']",
 "['python', 'spark', 'git', 'github']",
 "['python', 'r', 'databricks', 'spark', 'jira', 'confluence']",
 "['excel', 'powerpoint']",
 "['sql', 'sas', 'sas', 'python', 'excel', 'tableau']",
 "['tableau']",
 "['python', 'sql', 'azure', 'aws', 'kafka', 'spark', 'terraform']",
 "['python', 'sql', 'aws', 'azure', 'gcp', 'django', 'flask', 'docker']",
 "['sql', 'python', 'scala', 'pyspark']",
 "['sql', 'python', 'databricks', 'azure', 'pyspark', 'pandas', 'airflow', 'power bi']",
 "['python', 'sql', 'aws', 'gcp', 'azure', 'kafka', 'airflow', 'spark', 'tableau']",
 "['c', 'r', 'sql', 'python', 'aws', 'azure', 'hadoop', 'tableau']",
 "['outlook', 'excel', 'word', 'powerpoint', 'power bi', 'tableau']",
 "['python', 'sql', 'aws', 'redshift', 'snowflake', 'kafka', 'spark', 'pyspark', 'airflow', 'splunk', 'gitlab']",
 "['sql', 'python', 'r', 'c++', 'java', 'scala', 'shell', 'sap', 'power bi', 'alteryx', 'github']",
 "['python', 'bash', 'go', 'solidity', 'gcp', 'aws', 'airflow', 'spark', 'docker', 'github']",
 "['scala', 'java', 'spark', 'kafka']",
 "['sql']",
 "['sql', 'excel']",
 "['windows']",
 "['sql', 'sql server', 'azure', 'ssis']",
 None,
 "['sql', 'python', 'r', 'sql server', 'azure', 'power bi', 'git']",
 "['sql', 'c#', 'sql server', 'azure', 'ssis', 'power bi', 'dax', 'flow']",
 "['r']",
 "['python']",
 "['sql', 'mongo', 'python', 'solidity', 'elasticsearch', 'redis', 'cassandra', 'hadoop', 'git', 'gitlab']",
 "['python', 'sql', 'r', 'git']",
 None,
 "['sql', 'excel', 'visio', 'powerpoint', 'word']",
 "['tableau']",
 "['python', 'sql', 'aws', 'kubernetes', 'terraform']",
 "['sql', 'python', 'mysql', 'postgresql', 'sql server', 'snowflake', 'aws', 'git', 'jira']",
 "['sas', 'sas', 'r']",
 "['splunk']",
 None,
 None,
 "['vba', 'python', 'hadoop', 'kafka', 'power bi', 'sap']",
 "['power bi']",
 "['nosql', 'cassandra', 'couchbase', 'express', 'phoenix', 'redhat', 'linux', 'git', 'jira']",
 "['nosql', 'sql', 'python', 'java', 'javascript', 'scala', 'azure', 'aws', 'spark', 'pyspark', 'terraform']",
 "['python', 'sql', 'nosql', 'elasticsearch', 'hadoop', 'spark', 'kafka', 'numpy', 'scikit-learn', 'keras', 'tensorflow', 'pytorch', 'tableau']",
 "['sql', 'excel', 'alteryx', 'power bi']",
 "['sql', 'nosql', 'azure', 'power bi']",
 "['sql', 'python', 'gcp', 'flow']",
 "['python', 'r', 'php', 'javascript', 'typescript', 'java', 'c', 'swift', 'kotlin', 'hadoop', 'spark', 'react', 'spring', 'ionic', 'symfony', 'angular', 'qlik', 'tableau', 'yarn']",
 "['sql', 'spark', 'tableau']",
 "['python', 'java', 'sql', 'gcp', 'bigquery', 'airflow']",
 None,
 "['sql', 'sql server', 'excel']",
 None,
 "['sql', 'power bi', 'dax']",
 "['sql', 'python', 'java', 'mysql', 'postgresql', 'aws', 'gcp', 'airflow']",
 "['sql', 'python', 'sas', 'sas', 'r', 'matlab', 'snowflake']",
 "['python', 'c++', 'pytorch', 'tensorflow', 'nltk', 'docker', 'kubernetes']",
 "['sql']",
 "['r', 'electron']",
 "['python', 'sql', 'postgresql', 'gcp', 'aws', 'linux']",
 "['python', 'sql', 'java', 'aws', 'hadoop', 'spark', 'kafka', 'gdpr', 'yarn', 'docker', 'kubernetes', 'github']",
 "['excel', 'powerpoint', 'outlook', 'word']",
 "['python', 'azure', 'databricks', 'pyspark', 'pandas', 'hadoop', 'spark', 'nltk']",
 "['python', 'r', 'java', 'sql', 'azure', 'aws']",
 "['python', 'java', 'go', 'gcp', 'gdpr']",
 "['outlook']",
 "['python', 'javascript', 'nosql', 'mysql', 'aws', 'excel', 'git']",
 "['python', 'sql', 'nosql', 'hadoop', 'spark', 'kafka', 'tensorflow', 'pytorch']",
 "['python', 'ruby', 'ruby', 'sql', 'postgresql', 'redshift']",
 "['sql', 'oracle', 'tableau', 'power bi']",
 "['sql', 'python', 'sql server', 'aws', 'redshift', 'ssis']",
 "['python', 'r', 'sql', 'gcp', 'aws']",
 "['powerpoint', 'excel', 'word', 'spss']",
 "['sas', 'sas']",
 "['matlab', 'sql', 'sap']",
 "['sql', 'snowflake', 'sap']",
 None,
 "['python', 'r', 'scala', 'aws', 'azure', 'pandas', 'matplotlib']",
 "['python', 'r', 'sql', 'looker', 'tableau']",
 "['sql', 'python', 'hadoop', 'spark']",
 "['sql', 'python', 'azure', 'ssis', 'tableau', 'power bi']",
 None,
 "['sql', 'r', 'python', 'matlab', 'c++', 'spark']",
 "['nosql', 'java', 'python', 'scala', 'sql', 'aws', 'spark', 'hadoop', 'gitlab']",
 "['go']",
 "['python', 'go', 'sql', 'airflow', 'kafka', 'spark', 'vue', 'git', 'kubernetes', 'docker', 'jira']",
 None,
 "['python', 'sql', 'aws']",
 "['java', 'scala', 'sql', 'nosql', 'aws', 'gcp', 'azure', 'spark', 'kafka', 'bitbucket', 'git', 'jira']",
 "['node']",
 "['python', 'sql', 'gcp', 'aws', 'azure', 'spark', 'jenkins', 'docker', 'kubernetes']",
 "['nosql', 'sql', 'javascript', 'python', 'bigquery', 'gcp', 'hadoop', 'spark']",
 "['sql', 'python', 'perl', 'javascript', 'shell', 'gcp', 'ansible', 'terraform']",
 None,
 "['nosql', 'sql', 'python', 'java', 'scala', 'aws', 'azure', 'gcp', 'hadoop', 'spark', 'kafka', 'git', 'jenkins', 'ansible', 'docker', 'terraform', 'kubernetes']",
 None,
 "['go', 'flow']",
 "['excel']",
 "['python', 'snowflake', 'selenium', 'bitbucket', 'jenkins', 'git', 'jira', 'confluence']",
 "['shell', 'python', 'aws', 'snowflake', 'oracle', 'spark', 'pyspark', 'airflow']",
 "['python', 'sql', 'postgresql', 'airflow', 'fastapi', 'docker', 'git']",
 "['sql', 'python', 'scala', 'nosql', 'shell', 'cassandra', 'aws', 'gcp', 'snowflake', 'kafka', 'spark', 'hadoop', 'git']",
 None,
 "['r', 'python', 'sql']",
 "['sql', 'javascript', 'python', 'r']",
 "['python', 'sql', 'scala', 'java', 'databricks', 'aws', 'gcp', 'azure', 'pyspark', 'airflow', 'docker', 'kubernetes']",
 "['sql', 'python', 'scala', 'pyspark']",
 "['python', 'aws', 'pyspark', 'hadoop', 'spark', 'kafka', 'airflow']",
 "['nosql', 'sql']",
 "['java', 'scala', 'python', 'sql']",
 "['scala', 'python', 'java', 'aws', 'snowflake', 'spark', 'kafka', 'docker', 'ansible', 'terraform']",
 "['sql', 'python', 'sql server', 'oracle', 'azure', 'ssis']",
 "['python', 'sql', 'sql server']",
 "['sql', 'python', 'bigquery', 'snowflake', 'gcp', 'aws', 'airflow', 'looker', 'terraform']",
 "['typescript', 'sql', 'node.js', 'angular', 'docker', 'kubernetes']",
 "['python', 'r', 'sql', 'cassandra', 'azure', 'aws', 'scikit-learn', 'pytorch', 'matplotlib', 'tableau']",
 "['sql', 'shell', 'python', 'db2', 'sql server', 'cassandra', 'oracle', 'azure', 'databricks', 'linux']",
 "['nosql', 'r', 'sql', 'python', 'sas', 'sas', 'matlab', 'c', 'azure', 'aws', 'kafka', 'hadoop', 'tensorflow']",
 "['java', 'r', 'julia', 'python', 'power bi']",
 None,
 "['sql', 't-sql', 'c#', 'html', 'css', 'javascript', 'sql server']",
 "['css', 'javascript', 'c#', 'java', 'python', 'php', 'sql', 'mongodb', 'mongodb', 'fortran', 'r', 'mysql', 'react', 'jquery', 'asp.net', 'angular', 'node.js']",
 None,
 "['go', 'sql', 'azure', 'gcp', 'gdpr', 'looker', 'terraform']",
 "['excel']",
 "['aws', 'redshift']",
 "['python', 'numpy', 'pandas', 'tensorflow']",
 None,
 "['nosql', 'mongo', 'mongodb', 'mongodb']",
 "['sql', 'excel']",
 "['c']",
 "['html', 'gdpr', 'excel']",
 "['r', 'python', 'sql', 'pandas', 'numpy']",
 "['python', 'matlab', 'c++', 'sql', 'tableau']",
 "['sql', 'python', 'shell', 'dynamodb', 'aws', 'redshift', 'aurora', 'linux', 'windows']",
 "['sql', 'python', 'r', 'sql server', 'postgresql', 'mysql', 'dynamodb', 'aws', 'aurora', 'azure', 'redshift', 'jupyter', 'ssis', 'tableau']",
 "['python', 'hadoop', 'spark', 'kafka']",
 "['no-sql', 'sql', 'sql server', 'kafka', 'spark', 'power bi', 'qlik', 'tableau', 'excel', 'word', 'powerpoint']",
 "['sql', 'sql server', 'snowflake', 'bigquery', 'tableau']",
 "['sql']",
 None,
 "['go', 'sql', 'aws', 'snowflake', 'tableau', 'looker', 'word']",
 "['unix']",
 "['python', 'sql']",
 "['excel']",
 "['sql', 'excel']",
 "['java', 'python', 'sql']",
 "['scala', 'java', 'aws', 'snowflake', 'airflow', 'spark', 'looker', 'tableau', 'terraform', 'docker', 'kubernetes', 'github', 'git']",
 "['sql']",
 "['python', 'sql', 'pandas', 'numpy', 'matplotlib', 'scikit-learn']",
 "['aws']",
 None,
 "['python', 'sql', 'shell', 'ibm cloud', 'linux']",
 "['sql', 'nosql', 'python', 'java', 'azure', 'databricks', 'snowflake']",
 "['sql', 'r', 'python', 'excel']",
 "['azure']",
 None,
 "['sql', 'python', 'r', 'power bi']",
 "['python', 'r', 'linux', 'git']",
 "['sql', 'sap', 'power bi', 'tableau']",
 "['sql']",
 "['sql', 'python', 'snowflake', 'redshift', 'aws', 'airflow', 'spark', 'tableau', 'gitlab']",
 "['sql', 'r', 'python', 'go', 'aws', 'excel', 'alteryx']",
 "['sql', 'java', 'python', 'sql server', 'power bi']",
 "['python', 'aws']",
 "['sql', 'power bi', 'tableau']",
 "['c']",

In [28]:
import ast

ast.literal_eval(df['job_skills'].iloc[0])

ValueError: malformed node or string: None

In [38]:
df['job_skills'] = ast.literal_eval(df['job_skills'])

ValueError: malformed node or string: 0                                                      None
1                [r, python, sql, nosql, power bi, tableau]
2         [python, sql, c#, azure, airflow, dax, docker,...
3         [python, c++, java, matlab, aws, tensorflow, k...
4         [bash, python, oracle, aws, ansible, puppet, j...
                                ...
785736    [bash, python, perl, linux, unix, kubernetes, ...
785737                               [sas, sas, sql, excel]
785738                                  [powerpoint, excel]
785739    [python, go, nosql, sql, mongo, shell, mysql, ...
785740                                          [aws, flow]
Name: job_skills, Length: 785741, dtype: object

In [40]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)

df['job_skills'] = df['job_skills'].apply(clean_list)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
df[pd.isna(df['job_skills'])]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,salary_year_inflated
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None,NaN
21,Data Scientist,Stage - data scientist – génération ia de donn...,"Asnières-sur-Seine, France",via Jobijoba,Full-time,False,France,2023-02-23 13:41:21,False,False,France,None,NaN,NaN,Credit Agricole,None,None,NaN
26,Data Engineer,Data Engineer,United States,via LinkedIn,Full-time,False,Georgia,2023-09-15 13:56:18,True,False,United States,None,NaN,NaN,Infinite Computer Solutions,None,None,NaN
29,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Exusia,Full-time,False,India,2023-03-26 13:16:20,False,False,India,None,NaN,NaN,Exusia,None,None,NaN
36,Data Analyst,Data Analyst,"Des Moines, IA",via Trabajo.org,Full-time,False,"Illinois, United States",2023-11-06 13:01:22,False,True,United States,None,NaN,NaN,Assuredpartners,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785713,Cloud Engineer,"Data Center Chief Engineer, AWS Infrastructure...","Bangkok, Thailand",melalui LinkedIn,Pekerjaan tetap,False,Thailand,2023-03-12 06:37:47,False,False,Thailand,None,NaN,NaN,Amazon Web Services (AWS),None,None,NaN
785715,Data Analyst,Amul Careers 2023 - Apply Online - Data Analys...,India,melalui Jobsleworld - Jobs In India - Job Vaca...,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,None,NaN,NaN,Amul,None,None,NaN
785718,Business Analyst,Senior Performance QA Analyst,India,melalui BeBee India,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,None,NaN,NaN,Diebold Nixdorf,None,None,NaN
785724,Data Engineer,Junior Consultant Data Engineering,"Koln, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,False,False,Germany,None,NaN,NaN,Target Reply,None,None,NaN
785729,Data Engineer,Data Engineer Marketing Intelligence,Jerman,melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,IU Internationale Hochschule,None,None,NaN

In [46]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)   # ast.literal_eval() is already working, so theres an error. I ran this function twice

df['job_skills'] = df['job_skills'].apply(clean_list)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [45]:
df['job_skills'][1]

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [44]:
type(df['job_skills'][1])

list

In [47]:
df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list))

ValueError: malformed node or string: None

In [51]:
df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Calculate projected salary next year

Senior roles assume 5%

Other roles assume 3%

In [52]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [53]:
help(df.apply)

Help on method apply in module pandas.core.frame:

apply(func: 'AggFuncType', axis: 'Axis' = 0, raw: 'bool' = False, result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None, args=(), by_row: "Literal[False, 'compat']" = 'compat', engine: "Literal['python', 'numba']" = 'python', engine_kwargs: 'dict[str, bool] | None' = None, **kwargs) method of pandas.core.frame.DataFrame instance
    Apply a function along an axis of the DataFrame.

    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument.

    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:

        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.

    raw : bool, default False
        Determines if row or column is passed as a Series or ndarray object:

        * ``False`` : passes each row or column as a Series to the
          function.
        * ``True`` : the passed function will receive ndarray objects
          instead.
          If you are just applying a NumPy reduction function this will
          achieve much better performance.

    result_type : {'expand', 'reduce', 'broadcast', None}, default None
        These only act when ``axis=1`` (columns):

        * 'expand' : list-like results will be turned into columns.
        * 'reduce' : returns a Series if possible rather than expanding
          list-like results. This is the opposite of 'expand'.
        * 'broadcast' : results will be broadcast to the original shape
          of the DataFrame, the original index and columns will be
          retained.

        The default behaviour (None) depends on the return value of the
        applied function: list-like results will be returned as a Series
        of those. However if the apply function returns a Series these
        are expanded to columns.
    args : tuple
        Positional arguments to pass to `func` in addition to the
        array/series.
    by_row : False or "compat", default "compat"
        Only has an effect when ``func`` is a listlike or dictlike of funcs
        and the func isn't a string.
        If "compat", will if possible first translate the func into pandas
        methods (e.g. ``Series().apply(np.sum)`` will be translated to
        ``Series().sum()``). If that doesn't work, will try call to apply again with
        ``by_row=True`` and if that fails, will call apply again with
        ``by_row=False`` (backward compatible).
        If False, the funcs will be passed the whole Series at once.

        .. versionadded:: 2.1.0

    engine : {'python', 'numba'}, default 'python'
        Choose between the python (default) engine or the numba engine in apply.

        The numba engine will attempt to JIT compile the passed function,
        which may result in speedups for large DataFrames.
        It also supports the following engine_kwargs :

        - nopython (compile the function in nopython mode)
        - nogil (release the GIL inside the JIT compiled function)
        - parallel (try to apply the function in parallel over the DataFrame)

          Note: Due to limitations within numba/how pandas interfaces with numba,
          you should only use this if raw=True

        Note: The numba compiler only supports a subset of
        valid Python/numpy operations.

        Please read more about the `supported python features
        <https://numba.pydata.org/numba-doc/dev/reference/pysupported.html>`_
        and `supported numpy features
        <https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html>`_
        in numba to learn what you can or cannot use in the passed function.

        .. versionadded:: 2.2.0

    engine_kwargs : dict
        Pass keyword arguments to the engine.
        This is currently only used by the numba engine,
        see the documentation for the engine argument for more information.
    **kwargs
        Additional keyword arguments to pass as keywords arguments to
        `func`.

    Returns
    -------
    Series or DataFrame
        Result of applying ``func`` along the given axis of the
        DataFrame.

    See Also
    --------
    DataFrame.map: For elementwise operations.
    DataFrame.aggregate: Only perform aggregating type operations.
    DataFrame.transform: Only perform transforming type operations.

    Notes
    -----
    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    Examples
    --------
    >>> df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
    >>> df
       A  B
    0  4  9
    1  4  9
    2  4  9

    Using a numpy universal function (in this case the same as
    ``np.sqrt(df)``):

    >>> df.apply(np.sqrt)
         A    B
    0  2.0  3.0
    1  2.0  3.0
    2  2.0  3.0

    Using a reducing function on either axis

    >>> df.apply(np.sum, axis=0)
    A    12
    B    27
    dtype: int64

    >>> df.apply(np.sum, axis=1)
    0    13
    1    13
    2    13
    dtype: int64

    Returning a list-like will result in a Series

    >>> df.apply(lambda x: [1, 2], axis=1)
    0    [1, 2]
    1    [1, 2]
    2    [1, 2]
    dtype: object

    Passing ``result_type='expand'`` will expand list-like results
    to columns of a Dataframe

    >>> df.apply(lambda x: [1, 2], axis=1, result_type='expand')
       0  1
    0  1  2
    1  1  2
    2  1  2

    Returning a Series inside the function is similar to passing
    ``result_type='expand'``. The resulting column names
    will be the Series index.

    >>> df.apply(lambda x: pd.Series([1, 2], index=['foo', 'bar']), axis=1)
       foo  bar
    0    1    2
    1    1    2
    2    1    2

    Passing ``result_type='broadcast'`` will ensure the same shape
    result, whether list-like or scalar is returned by the function,
    and broadcast it along the axis. The resulting column names will
    be the originals.

    >>> df.apply(lambda x: [1, 2], axis=1, result_type='broadcast')
       A  B
    0  1  2
    1  1  2
    2  1  2

In [55]:
df_salary

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,salary_year_inflated
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd...",112785.00
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac...",144200.00
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}",123600.00
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr...",235068.66
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro...",91670.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab...",143392.48
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",None,None,154500.00
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':...",228531.25
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ...",162225.00
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}",162225.00

In [58]:
def projected_salary(row):
    if "Senior" in row['job_title_short']:
        return 1.05 * row['salary_year_avg']
    else:
        return 1.03 * row['salary_year_avg']

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis = 1)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]

In [60]:
df_salary['salary_year_inflated'] = df_salary.apply(lambda row: 1.05 * row['salary_year_avg'] if 'Senior' in row['job_title_short'] else 1.03 * row['salary_year_avg'], axis = 1)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]